osx_image: xcode7.3
language: objective-c
before_install:
- gem install cocoapods
- pod repo add tulapps https://github.com/tulapps/Specs
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/UnsplashKit.xcworkspace -scheme UnsplashKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
